name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Update
      run: sudo apt-get update

    - name: Install OpenGL dev
      run: sudo apt-get install -y xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install X11 dev
      run: sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev

    - name: Install ALSA dev
      run: sudo apt-get install -y libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install -y libpulse-dev

    - name: Install Pango dev
      run: sudo apt-get install -y libpango1.0-dev

    - name: Install Wayland
      run: sudo apt-get install -y libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libegl-dev libgtk-3-dev

    - name: Install openssl
      run: sudo apt-get install -y openssl
      
    - name: Install ninja-build
      run: sudo apt-get install -y ninja-build
      
    - name: Install gettext
      run: sudo apt-get install -y gettext
      
    - name: Install python dependencies
      run: sudo apt-get install -y libssl-dev libffi-dev
      
    - name: Setup environment
      run: >
        echo "$PWD/BUILD-Linux-amd64/Release/install/bin" >> $GITHUB_PATH &&
        echo "LD_LIBRARY_PATH=$PWD/BUILD-Linux-amd64/Release/install/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build mrv2
      run: >
        ./runme_nolog.sh


  windows-build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -D TLRENDER_USD=OFF


  linux-minimal-build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Update
      run: sudo apt-get update

    - name: Install OpenGL dev
      run: sudo apt-get install -y xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install X11 dev
      run: sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev

    - name: Install ALSA dev
      run: sudo apt-get install -y libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install -y libpulse-dev

    - name: Install Pango dev
      run: sudo apt-get install -y libpango1.0-dev

    - name: Install Wayland
      run: sudo apt-get install -y libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libegl-dev libgtk-3-dev

    - name: Install openssl
      run: sudo apt-get install -y openssl
      
    - name: Install ninja-build
      run: sudo apt-get install -y ninja-build
      
    - name: Install gettext
      run: sudo apt-get install -y gettext
      
    - name: Install python dependencies
      run: sudo apt-get install -y libssl-dev libffi-dev
      
    - name: Setup environment
      run: >
        echo "$PWD/BUILD-Linux-amd64/Release/install/bin" >> $GITHUB_PATH &&
        echo "LD_LIBRARY_PATH=$PWD/BUILD-Linux-amd64/Release/install/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -D TLRENDER_USD=OFF -D TLRENDER_FFMPEG=OFF -D TLRENDER_RAW=OFF -D TLRENDER_TIFF=OFF -D TLRENDER_AUDIO=OFF -D MRV2_PDF=OFF -D MRV2_NETWORK=OFF -D MRV2_PYBIND11=OFF -D BUILD_PYTHON=OFF

  macos-build:
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install ninja-build
      run: brew install ninja
      
    - name: Install automake
      run: brew install automake

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install libffi openssl readline sqlite3 xz zlib

    - name: Setup environment
      run: >
        mkdir -p "$PWD/BUILD-Darwin-amd64/Release/install/bin/" &&
        ln -s /usr/bin/true "$PWD/BUILD-Darwin-amd64/Release/install/bin/makeinfo" &&
        echo "$PWD/BUILD-Darwin-amd64/Release/install/bin:/usr/local/bin" >> $GITHUB_PATH

    - name: Build mrv2
      run: >
        ./runme_nolog.sh dist


  macos-quick-build:
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install ninja-build
      run: brew install ninja

    - name: Install openssl
      run: brew install openssl
      
    - name: Install automake
      run: brew install automake

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install openssl readline sqlite3 xz zlib

    - name: Setup environment
      run: >
        mkdir -p "$PWD/BUILD-Darwin-amd64/Release/install/bin/" &&
        ln -s /usr/bin/true "$PWD/BUILD-Darwin-amd64/Release/install/bin/makeinfo" &&
        echo "$PWD/BUILD-Darwin-amd64/Release/install/bin:/usr/local/bin" >> $GITHUB_PATH

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -v -D TLRENDER_USD=OFF

  macos-minimal-build:
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install ninja-build
      run: brew install ninja

    - name: Install openssl
      run: brew install openssl
      
    - name: Install automake
      run: brew install automake

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install openssl readline sqlite3 xz zlib

    - name: Setup environment
      run: >
        mkdir -p "$PWD/BUILD-Darwin-amd64/Release/install/bin/" &&
        ln -s /usr/bin/true "$PWD/BUILD-Darwin-amd64/Release/install/bin/makeinfo" &&
        echo "$PWD/BUILD-Darwin-amd64/Release/install/bin:/usr/local/bin" >> $GITHUB_PATH

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -D TLRENDER_USD=OFF -D TLRENDER_FFMPEG=OFF -D TLRENDER_RAW=OFF -D TLRENDER_TIFF=OFF -D TLRENDER_AUDIO=OFF -D MRV2_PDF=OFF -D MRV2_NETWORK=OFF -D MRV2_PYBIND11=OFF -D BUILD_PYTHON=OFF

  windows-gpl-build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -gpl -D TLRENDER_USD=OFF

  windows-minimal-build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit

    - name: Build mrv2
      run: >
        ./runme_nolog.sh -D TLRENDER_USD=OFF -D TLRENDER_FFMPEG=OFF -D TLRENDER_RAW=OFF -D TLRENDER_TIFF=OFF -D TLRENDER_AUDIO=OFF -D MRV2_PDF=OFF -D MRV2_NETWORK=OFF -D MRV2_PYBIND11=OFF -D BUILD_PYTHON=OFF
