name: Full Builds MacOS 12

on: [push]

jobs:
  ###################################
  #                                 #
  # FULL BUILDS                     #
  #                                 #
  ###################################
  macos-full-build:
    runs-on: macos-12

    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get machine name
      run: |
        echo "Machine name: $RUNNER_NAME"

    - name: Install ninja-build
      run: brew install ninja
      
    - name: Install automake
      run: brew install automake
      
    - name: Install meson
      run: brew install meson

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install libb2 libffi readline sqlite3 xz zlib
        
    - name: Install pyFLTK dependencies
      run: brew install subversion swig
      
    - name: Setup environment
      run: mkdir -p ssh

    - name: Decode SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh/id_rsa
      shell: bash
  
    - name: Set permissions on SSH key
      run: chmod 600 ssh/id_rsa
      
    - name: Set executable permissions
      run: |
        chmod +x ./*.sh ./bin/*.sh ./etc/*.sh

    # - name: Install cmake
    #   run: |
    #     ./etc/install_cmake.sh

    - name: Build mrv2
      run: |
        ./runme_nolog.sh -t package
      
    - name: Upload binaries  # Conditional step
      run: |
        ./bin/upload_sourceforge.sh
