name: MacOS M1

on: [push]

jobs:
  ###################################
  #                                 #
  # FULL BUILDS                     #
  #                                 #
  ###################################
  macos-14-full-build:
    runs-on: macos-14

    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 14.0
      
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get machine name
      run: |
        echo "Machine name: $RUNNER_NAME"

    - name: Install ninja-build
      run: brew install ninja
      
    - name: Install automake
      run: brew install automake curl

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install libb2 libffi readline sqlite3 xz zlib
      
    - name: Reinstall xz to avoid broken macOS 14
      run: brew reinstall xz
        
    - name: Install pyFLTK dependencies
      run: brew install swig
      
        
    # Download and install Vulkan SDK with MoltenVK
    - name: Install Vulkan SDK
      if: github.ref_name == 'vulkan'
      run: |
        # Example: Replace with your method of getting the latest version
        VULKAN_VERSION="1.4.309.0"
          
        VULKAN_SDK_URL="https://sdk.lunarg.com/sdk/download/${VULKAN_VERSION}/mac/vulkansdk-macos-${VULKAN_VERSION}.dmg"
          
        curl -LO "${VULKAN_SDK_URL}"
        echo "Download done"
        
        hdiutil attach "vulkansdk-macos-${VULKAN_VERSION}.dmg"

        # Find the mount point dynamically
        MOUNT_POINT=$(hdiutil info | grep "image-path.*vulkansdk-macos-${VULKAN_VERSION}.dmg" | grep -o "/Volumes/.*")

        sudo installer -pkg "${MOUNT_POINT}/vulkansdk-macos-${VULKAN_VERSION}.pkg" -target ~/VulkanSDK

        # Set environment variables
        echo "VULKAN_SDK=~/VulkanSDK" >> $GITHUB_ENV
        echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "~/VulkanSDK/macOS/bin" >> $GITHUB_PATH

    # Verify Vulkan installation
    - name: Verify Vulkan
      run: |
        echo "VULKAN_SDK: $VULKAN_SDK"
        echo "PATH: $PATH"
        echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
        vulkaninfo --summary
        
    - name: Setup environment
      run: mkdir -p ssh

    - name: Decode SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh/id_rsa
      shell: bash
  
    - name: Set permissions on SSH key
      run: chmod 600 ssh/id_rsa
      
    - name: Set executable permissions
      run: |
        chmod +x ./*.sh ./bin/*.sh ./etc/*.sh ./bin/release/*.sh

    # - name: Install cmake
    #   run: |
    #     ./etc/install_cmake.sh

    - name: Build mrv2
      run: |
        ./etc/runme_nolog.sh -t package

    - name: Upload binaries  # Conditional step
      if: github.ref_name == 'beta'
      run: |
        ./bin/release/upload_sourceforge.sh
