name: MacOS 14

on: [push]

jobs:
  ###################################
  #                                 #
  # FULL BUILDS                     #
  #                                 #
  ###################################
  macos-14-full-build:
    runs-on: macos-14

    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 14.0
      
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get machine name
      run: |
        echo "Machine name: $RUNNER_NAME"

    - name: Check hdiutil
      run: |
        hdiutil info
        hdiutil create -size 10m -fs HFS+ -volname test_disk test.dmg
        hdiutil attach test.dmg
        hdiutil detach /Volumes/test_disk
        rm test.dmg
      
    - name: Install ninja-build
      run: brew install ninja
      
    - name: Install automake
      run: brew install automake curl

    - name: Install meson
      run: brew install meson
      
    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install libb2 libffi readline sqlite3 xz zlib
      
    - name: Reinstall xz to avoid broken macOS 14
      run: brew reinstall xz
        
    - name: Install pyFLTK dependencies
      run: brew install subversion swig
      
    - name: Setup environment
      run: mkdir -p ssh

    - name: Decode SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh/id_rsa
      shell: bash
  
    - name: Set permissions on SSH key
      run: chmod 600 ssh/id_rsa
      
    - name: Set executable permissions
      run: |
        chmod +x ./*.sh ./bin/*.sh ./etc/*.sh ./bin/release/*.sh

    # - name: Install cmake
    #   run: |
    #     ./etc/install_cmake.sh

    - name: Build mrv2
      run: |
        ./etc/runme_nolog.sh -t package

    - name: Upload binaries  # Conditional step
      run: |
        ./bin/release/upload_sourceforge.sh
